version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your_local_secret_key
    volumes:
      - ./app:/app
